### ISSUE TITLE
Deno doesnt work with Vercel and OAK

### ISSUE THREAD

**Issue by Lumca** [TooTallNate/vercel-deno#54]
Hello,

I got a simple API written in DENO with OAK and mongo.
When I try to get a response from Vercel CLI. It is working flawlessly.
But when deployed to VERCEL and trying it on their servers I always get:
`error: Uncaught (in promise) Error: Read-only file system (os error 30)
    at processResponse (core.js:223:11)
    at Object.jsonOpAsync (core.js:240:12)
    at async Object.mkdir (deno:cli/rt/30_fs.js:100:5)
    at async download (mod.ts:45:5)
    at async prepare (mod.ts:65:21)
    at async init (util.ts:44:3)
    at async mod.ts:14:1
RequestId: dc8fcabe-3313-4123-ae10-ef294a38c02e Error: Runtime exited with error: exit status 1
Runtime.ExitError` 

Did anyone faced this error too?

**Comment by TooTallNate** [comment]
It looks like you're running into [this same issue](https://github.com/TooTallNate/vercel-deno/issues/40#issuecomment-706491285). This is supposedly fixed by https://github.com/manyuanrong/deno-plugin-prepare/pull/29. Can you make sure that you are using `deno-plugin-prepare` v0.8.0 or newer?

**Comment by TooTallNate** [comment]
Closing due to inactivity.
